
language: node_js
os: linux
dist: xenial
addons:
  apt:
    update: true
    packages:
      - php7.0
      - netcat-traditional
node_js: 9
install: npm install -g ottomatica/docable
script: docable report unix-service/steps.yml
