version: 2
jobs:
  build:
    machine:
      php:
        version: 7.1
      node:
        version: v10.16.0
    steps:
      - checkout
      - run: npm install -g ottomatica/docable
      - run: docable report unix-service/steps.yml
