version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: nvm install v10.16.0 && nvm use v10.16.0
      - run: npm install -g ottomatica/docable
      - run: docable report unix-service/steps.yml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build