version: 2
jobs:
  build:
    # docker:
    #   - image: misterio92/ci-php-node
    machine: true
    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get update && apt-get install -y netcat-openbsd
      - run: npm install -g ottomatica/docable
      - run: docable report unix-service/steps.yml
      - run: cd engine && npm install && node lintmd.js ../unix-service
      - run: cd engine && npm install && node lintmd.js render ../unix-service --render learnk8s
      - store_artifacts:
          path: unix-service/docable_results/unix-service.html

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: 
                - master
