version: 2
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: npm install -g ottomatica/docable
      - run: docable report unix-service/steps.yml
