version: 2
jobs:
  build:
    branches:
      only:
        - master  
    docker:
     - image: misterio92/ci-php-node
    steps:
      - checkout
      - run: npm install -g ottomatica/docable
      - run: docable report unix-service/steps.yml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build